### PR TITLE
NZSL-50: Search official signs using a SQLite dump of Signbank data imported into the repository

### PR DESCRIPTION
**Pull request by joshmcarthur**
This pull request refactors the search feature of NZSL Share to match signs in Signbank, rather than Freelex. At this stage, the ability to use Freelex or Signbank is switchable via a ENV-var based feature flag. My plan is to release this, then switch one environment at a time over to Signbank, and test. Assuming everything is OK, we'll leave it in Signbank mode until February, then remove the Freelex branch. If anything goes wrong with the data we are exporting in Signbank, we can revert to use Freelex.

Most of the complexity here was refactoring the search service(s) to support 3 data sources instead of 2, and adding the ability to switch between them. The Signbank search SQL is quite different compared to the other searches, because the query must be compatible with SQLite, rather than Postgres. I tried to get this working rather than importing data from SQLite into Postgres because the NZSL dictionary Rails app will need a very similar implementation for it's keyword search, and I figured I'd get the dev effort out of the way early.

For now, I have committed the SQLite database to the repository. I do a small DDL operation when the app starts to define a [generated column](https://www.sqlitetutorial.net/sqlite-generated-columns/) so that we can refer to the `gloss` column as `word`. This allows the sorting to be changed between alphabetic (ASC or DESC), and relevance. Popular and recent sorts are not available for signbank signs. Technically, Freelex supports a search based on recency of publishing, but we don't have publish dates from Signbank, and I don't think anyone uses that feature for official sign results in NZSL Share -only for community contributions. We have stories planned in the near future to update the SQLite database as part of the release process based on the latest [nzsl-dictionary-scripts release](https://github.com/ODNZSL/nzsl-dictionary-scripts/releases), which is why I've scripted the `ADD COLUMN` into an initialiser. This will allow the app to remain more up to date with the latest Signbank data.

### CODE REVIEW

**Comment by G-Rath** [comment]
Would be cool if you wouldn't mind rebasing to see if the new codeql workflow flags anything, but up to you :)

**Comment by joshmcarthur** [comment]
@G-Rath it doesn't look like it failed anything?

**Comment by G-Rath** [comment]
@joshmcarthur yup, looks like you're all good 😄

**Review by mischa-s — APPROVED** [review]
I don't have any context on this, but reading the code, nothing jumps out to me

**Pull request merged**
