### PR TITLE
NZSL-103: Backend: Add support for bulk operations, with topic assignment as an example

### PR DESCRIPTION
**Pull request by joshmcarthur**
This pull request implements the ability to perform batch operations on a collection of signs accessible to the user. There are two batch operations planned at this stage, but it's likely others will follow:

* NZSL-103: Bulk assign a topic to signs
* NZSL-104: Bulk submit signs for publishing

This pull request implements NZSL-103 along with the supporting code for more batch operations. Batch operations are represented by a model which accepts a callable operation to apply to each record, and an optional callable precondition. Records which successfully pass the precondition and apply the operation without raising are added to the array of successful records. Records which either fail the precondition or fail to apply the operation are added to the array of failed records. For this feature, it's sufficient to just report how many records succeeded and failed. Both preconditions and operations can add errors to the relevant records if necessary to communicate additional context.

Operations are implemented as methods in the controller for this moment, since there are only two of them planned. It would be trivial if this feature grows in scope to migrate these operations into dedicated service objects.

### CODE REVIEW

**Comment by joshmcarthur** [comment]
@hopkincame, @mischa-s you might be interested to know that I asked ChatGPT for how I could apply a bulk operation to a collection of records, reporting on which records succeeded and failed, what it produced is essentially unmodified in this PR (I also asked it for tests, which are also in here). I just wrapped the controller around it.

**Comment by mischa-s** [comment]
> @hopkincame, @mischa-s you might be interested to know that I asked ChatGPT for how I could apply a bulk operation to a collection of records, reporting on which records succeeded and failed, what it produced is essentially unmodified in this PR (I also asked it for tests, which are also in here). I just wrapped the controller around it.

NOOOO WAAAY. What did it actually produce? Can you post the exact answer? Did you tell it about signs and topics?

**Comment by joshmcarthur** [comment]
@mischa-s specifically I asked it the following prompts:

> Make a Ruby class that can apply a batch operation on a collection of records

> Can you have it return which records succeeded and which failed?

> Can you add an authorisation check to the operation?

> Call the authorisation a precondition

> Can you write RSpec tests for this class?

This yielded the `BatchOperation` class and tests, essentially as I've included here. The only thing I changed was to make precondition a keyword arg rather than a block argument, since I didn't think it was a clear API to have the precondition be an unlabelled block. I probably could have asked ChatGPT to do this for me as well.

I also asked for a controller to invoke this class, however I had less good results here, primarily because ChatGPT was not aware of what I intended to do. It would have been an interesting exercise to see if I could tell it what I wanted to do, but the controller it produced without that context was technically correct, but not at all what I needed:

```
class BatchOperationsController < ApplicationController
  def create
    records = params[:records]
    operation = params[:operation]
    precondition = params[:precondition]

    batch_operation = BatchOperation.new(records, operation, &precondition)
    success, failure = batch_operation.process

    render json: { success: success, failure: failure }
  end
end
```

```
require 'rails_helper'

describe BatchOperationsController, type: :request do
  let(:records) { [1, 2, 3, 4, 5] }
  let(:operation) { Proc.new { |record| puts "Processing record: #{record}" } }
  let(:precondition) { Proc.new { |record| record.even? } }
  let(:params) do
    {
      records: records,
      operation: operation,
      precondition: precondition
    }
  end

  describe 'POST #create' do
    it 'applies batch operation to records and returns result' do
      post batch_operations_path, params: params

      expect(response).to have_http_status(:ok)
      expect(JSON.parse(response.body)).to eq({ 'success' => [2, 4], 'failure' => [1, 3, 5] })
    end
  end
end
```

**Review by hopkincame — APPROVED** [review]
Approved once conflicts are resolved

**Pull request merged**
